### ISSUE TITLE
This logic should be in the original driver

### ISSUE THREAD

**Issue by georgysavva** [Kount/pq-timeouts#1]
Hi! I agree with you, that the absence of the read/write timeouts in the lib/pq is a serious drawback in HA environment. And it's really cool that you wrote a wrapper with such functional. But consider following situation: we have read timeout=2s, write timeout=2s, we have already opened connection and network failure occur, we send our query. We begin to wait for the response, imagine that the response size is 1024 bytes. because of the network failure db sends response with very high latency 1 byte per second, we call conn.read(1024) and we fit into read timeout, but we receive only 1 byte, therefore we need to call read 1024 times to receive the whole response.

In order to timeout worked as expected we shouldn't call conn.SetReadDeadline in every conn.Read call.
We should call conn.SetReadDeadline(2s) before any read operations. Therefore timeouts logic should be in the original driver. As in other libraries [https://github.com/go-pg/pg](url) for example.

**Comment by pneisen** [comment]
I agree and I tried to pull request this functionality into lib/pq, but the maintainers of lib/pq were not interested. This wrapper was a workaround.

That said, I think this issue is solved and this wrapper is not needed with the addition of context support to database/sql in Go 1.8.

**Comment by georgysavva** [comment]
As far as I know context doesn't work if driver doesn't implement cancellation logic.

**Comment by pneisen** [comment]
True, but I believe lib/pq implemented this logic in this pull request: https://github.com/lib/pq/pull/535
